sequenceDiagram
  participant participant_TabletopTable as TabletopTable
  participant participant_useZoraTheme as useZoraTheme
  participant_TabletopTable->>participant_useZoraTheme: useZoraTheme()
  participant_useZoraTheme-->>participant_TabletopTable: return
