graph TD
  package__ankhorage_zora_tabletop["@ankhorage/zora-tabletop"]
  entrypoint_src_index_ts["src/index.ts"]
  package__ankhorage_zora_tabletop --> entrypoint_src_index_ts
  module_src_index_ts["src/index.ts"]
