export const tabletopTableMeta = {
  name: 'TabletopTable',
  category: 'component',
  description: 'Arranges player seats and shared cards around a responsive tabletop surface.',
  directManifestNode: true,
  allowedChildren: [],
  blueprint: {
    label: 'Tabletop table',
    defaultProps: {
      seats: [],
      centerCards: [],
      shape: 'oval',
      cardSize: 'small',
    },
  },
  bindings: {
    props: {
      seats: {
        label: 'Seats',
        value: { type: 'array', itemType: 'object' },
        acceptsFallback: true,
        acceptsTransforms: true,
      },
      centerCards: {
        label: 'Center cards',
        value: { type: 'array', itemType: 'object' },
        acceptsFallback: true,
        acceptsTransforms: true,
      },
      centerLabel: {
        label: 'Center label',
        value: { type: 'string' },
        acceptsFallback: true,
        acceptsTransforms: true,
      },
      centerSublabel: {
        label: 'Center sublabel',
        value: { type: 'string' },
        acceptsFallback: true,
        acceptsTransforms: true,
      },
      disabled: {
        label: 'Disabled',
        value: { type: 'boolean' },
        acceptsFallback: true,
        acceptsTransforms: true,
      },
    },
  },
  props: {
    seats: {
      type: 'array',
      category: 'Players',
      label: 'Seats',
      default: [],
      authoring: { authority: 'instance' },
    },
    centerCards: {
      type: 'array',
      category: 'Table',
      label: 'Center cards',
      default: [],
      authoring: { authority: 'instance' },
    },
    centerLabel: {
      type: 'string',
      category: 'Table',
      label: 'Center label',
      authoring: { authority: 'instance' },
    },
    centerSublabel: {
      type: 'string',
      category: 'Table',
      label: 'Center sublabel',
      authoring: { authority: 'instance' },
    },
    shape: {
      type: 'enum',
      category: 'Table',
      label: 'Shape',
      enum: ['circle', 'oval', 'rounded'],
      default: 'oval',
      authoring: { authority: 'instance' },
    },
    seatCount: {
      type: 'enum',
      category: 'Players',
      label: 'Seat count',
      enum: [2, 3, 4, 5, 6, 7, 8, 9, 10],
      authoring: { authority: 'instance' },
    },
    cardSize: {
      type: 'enum',
      category: 'Cards',
      label: 'Card size',
      enum: ['small', 'medium', 'large'],
      default: 'small',
      authoring: { authority: 'instance' },
    },
    disabled: {
      type: 'boolean',
      category: 'State',
      label: 'Disabled',
      default: false,
      authoring: { authority: 'instance' },
    },
    accessibilityLabel: {
      type: 'string',
      category: 'Accessibility',
      label: 'Accessibility label',
      authoring: { authority: 'instance' },
    },
  },
} as const;
