name: Renovate

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize

permissions:
  contents: read
  pull-requests: read

jobs:
  changeset:
    if: >-
      (github.actor == 'renovate[bot]' || github.actor == 'ankhorage-renovate-sync[bot]') &&
      github.event.pull_request.head.repo.full_name == github.repository &&
      startsWith(github.event.pull_request.head.ref, 'renovate/')
    uses: ankhorage/renovate/.github/workflows/changeset.yml@10ec85a194746407f5c3a5dd4b62946d6aade6ef
    with:
      renovate_sync_client_id: ${{ vars.ANKHORAGE_RENOVATE_SYNC_CLIENT_ID }}
    secrets:
      renovate_sync_private_key: ${{ secrets.ANKHORAGE_RENOVATE_SYNC_PRIVATE_KEY }}
