name: Renovate

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize
      - labeled

concurrency:
  group: renovate-${{ github.repository }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

permissions:
  checks: read
  contents: read
  issues: read
  pull-requests: read
  statuses: read

jobs:
  changeset:
    if: >-
      (github.event.pull_request.user.login == 'renovate[bot]' || github.event.pull_request.user.login == 'ankhorage-renovate-sync[bot]') &&
      github.event.pull_request.head.repo.full_name == github.repository &&
      startsWith(github.event.pull_request.head.ref, 'renovate/')
    uses: ankhorage/renovate/.github/workflows/changeset.yml@041fd7dc18be02e0fd20911780a4762b3e3d60d1
    with:
      renovate_sync_client_id: ${{ vars.ANKHORAGE_RENOVATE_SYNC_CLIENT_ID }}
    secrets:
      renovate_sync_private_key: ${{ secrets.ANKHORAGE_RENOVATE_SYNC_PRIVATE_KEY }}
